import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "j-iv's blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-rows-[auto_auto_1fr] min-h-screen font-[family-name:var(--font-geist-sans)]">
          <header className="p-4 flex items-center justify-center sticky top-0 z-10 bg-white">
            <nav className={"flex justify-center items-center gap-4"}>
              <a href={"/"} className={"hover:underline"}>
                <strong>home </strong>
              </a>
                /
              <a href={"http://buymeacoffee.com/jishv"} className={"hover:underline"} target="_blank" rel="noopener noreferrer">
                <strong> buy me a coffee</strong>
              </a>
            </nav>
          </header>
          <div className={"mt-5 flex flex-col sm:flex-row items-center justify-center gap-3 sm:pl-10"}>
            <img
              src="/headshot.jpg"
              alt="profile picture"
              className={"rounded-full w-20 h-20 sm:w-24 sm:h-24 flex-shrink-0"}
            />
            <div className={"flex flex-col gap-1 items-center sm:items-start text-lg sm:text-xl leading-7 mt-1 sm:mt-0 px-4 sm:px-0 sm:pr-16"}>
              <h3 className={"text-2xl font-bold"}>jishnu.v</h3>
              <div className={"text-lg"}>engineer by profession and passion</div>
              <div className={"flex flex-row gap-2"}>
                <a href={"https://linkedin.com/in/jishnu-v"} target="_blank" rel="noopener noreferrer">
                  <img src="/linkedin-logo.png" alt={"LinkedIn profile link"} className={"w-5 h-5 flex-shrink-0 hover:opacity-70"}/>
                </a>
                <a href={"https://github.com/j-iv"} target="_blank" rel="noopener noreferrer">
                  <img src="/github-logo.png" alt={"Github profile link"} className={"w-5 h-5 flex-shrink-0 hover:opacity-70"}/>
                </a>
                <a href={"https://jishnu-v.medium.com/"} target="_blank" rel="noopener noreferrer">
                  <img src="/medium-logo.png" alt={"Medium profile link"} className={"w-5 h-5 flex-shrink-0 hover:opacity-70"}/>
                </a>
              </div>

            </div>
          </div>
          <main className={"mt-5 sm:mt-10 p-5 w-[90vw] max-w-[800px] mx-auto flex flex-col sm:flex-row gap-5 sm:gap-15"}>
            <aside className={"text-lg w-1/4"}>
              <ul className={"flex flex-row sm:flex-col gap-3"}>
                <li><strong>#java</strong></li>
                <li><strong>#springboot</strong></li>
              </ul>
            </aside>
            <section className={"flex flex-col gap-8"}>
              <article>
                <h2 className={"text-2xl pb-5 font-bold"}>blog 1</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                  incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                  exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                  fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa
                  qui officia deserunt mollit anim id est laborum.</p>
              </article>
              <article>
                <h2 className={"text-2xl pb-5 font-bold"}>blog 2</h2>
                <p> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
                  doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
                  veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam
                  voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur
                  magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est,
                  qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non
                  numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat
                  voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis
                  suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum
                  iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur,
                  vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
              </article>
            </section>
          </main>
        </div>
      </body>
    </html>
  );
}
