import type { Metadata } from "next";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "j-iv's blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-rows-[auto_auto_1fr] min-h-screen font-[family-name:var(--font-geist-sans)]">
          <header className="p-4 flex items-center justify-center sticky top-0 z-10 bg-white">
            <nav className={"flex justify-center items-center gap-4"}>
              <a href={"/"} className={"hover:underline"}>
                <strong>home </strong>
              </a>
              /
              <a
                href={"http://buymeacoffee.com/jishv"}
                className={"hover:underline"}
                target="_blank"
                rel="noopener noreferrer"
              >
                <strong> buy me a coffee</strong>
              </a>
            </nav>
          </header>
          <div
            className={
              "mt-5 flex flex-col sm:flex-row items-center justify-center gap-3 sm:pl-10"
            }
          >
            <Image
              src="/headshot.jpg"
              alt="profile picture"
              width={80}
              height={80}
              className={"rounded-full w-20 h-20 sm:w-24 sm:h-24 flex-shrink-0"}
            />
            <div
              className={
                "flex flex-col gap-1 items-center sm:items-start text-lg sm:text-xl leading-7 mt-1 sm:mt-0 px-4 sm:px-0 sm:pr-16"
              }
            >
              <h3 className={"text-2xl font-bold"}>jishnu.v</h3>
              <div className={"text-lg"}>
                engineer by profession and passion
              </div>
              <div className={"flex flex-row gap-2"}>
                <a
                  href={"https://linkedin.com/in/jishnu-v"}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src="/linkedin-logo.png"
                    alt={"LinkedIn profile link"}
                    width={20}
                    height={20}
                    className={"w-5 h-5 flex-shrink-0 hover:opacity-70"}
                  />
                </a>
                <a
                  href={"https://github.com/j-iv"}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src="/github-logo.png"
                    alt="Github profile link"
                    width={20}
                    height={20}
                    className="w-5 h-5 flex-shrink-0 hover:opacity-70"
                  />
                </a>
                <a
                  href={"https://jivv.medium.com/"}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src="/medium-logo.png"
                    alt={"Medium profile link"}
                    width={20}
                    height={20}
                    className={"w-5 h-5 flex-shrink-0 hover:opacity-70"}
                  />
                </a>
              </div>
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
